### ISSUE TITLE
foldConstants binop case with non-constants arguments after fold

### ISSUE THREAD

**Issue by larsk21** [larsk21/lean-praktikum-while#15]
Should the line in `foldConstants` be `| (a, b) => Expr.binop a op b` instead of `| _ => e`? Does it make a difference for the result? The `foldConstants_doesNotIncreaseExecTime` proof would get slightly simpler, the other proofs that I know are not affected.

**Comment by vwinkler** [comment]
It would break my proof. I'm not sure how difficult the fix would be.

**Comment by larsk21** [comment]
*Fixed* on all relevant branches.
