### ISSUE TITLE
Remove simps that do not close a goal

### ISSUE THREAD

**Issue by vwinkler** [larsk21/lean-praktikum-while#21]
Example: [see here](https://github.com/larsk21/lean-praktikum-while/blob/704dc9f584b80281c218a3ce21612d578ffb6f5a/TBA/While/Semantics.lean#L49).
Something like `simp only [hk, eqSelf, Lean.Simp.ite_True]` may be a solution in this case;
`simp only [hk, eqSelf, Lean.Simp.ite_False]` in respective cases.

**Comment by larsk21** [comment]
Agreed, but note that the last simp in a case or have block does not have to be a simp only.

**Comment by larsk21** [comment]
Done on both dependent type branches.
