### ISSUE TITLE
Should skip be removed if it was created by optimization of while(false) {...}?

### ISSUE THREAD

**Issue by vwinkler** [larsk21/lean-praktikum-while#3]
Is the example in [lines 185-188](https://github.com/larsk21/lean-praktikum-while/blob/687460dbe14b487bcb6bc7b73c0d70cc20b402a4/TBA/While/Solution.lean#L185-L188) a correct assertion?

**Comment by larsk21** [comment]
I would treat two programs with skips in different places as equal. For our tests I added a `clean` function to compare the programs without the skip commands.

**Comment by larsk21** [comment]
I agree, I didn't think of the runtime determinism. From a practical point of view, it would be a lot easier to just replace it with `skip`, but I'm not sure if this is correct in the sense of constant propagation.

**Comment by larsk21** [comment]
Since the previous approach was obviously wrong, I removed the `clean` function and added a macro rule for `Com.skip` inside of programs instead. This way we can continue discussing the correct way of removing a `while` without having to worry about failing tests, i.e. having a working state.

**Comment by vwinkler** [comment]
Thank you. I'd go with keeping the `skip` because it's easier and we could still adjust later.
