### ISSUE TITLE
`[Expr| false ] is a variable named "false"

### ISSUE THREAD

**Issue by vwinkler** [larsk21/lean-praktikum-while#4]
``#reduce `[Expr| false ]`` incorrectly prints `Expr.var "false"`, whereas ``#reduce `[Expr| true ]`` correctly prints `Expr.const (Val.bool true)`.

This causes [the assertion in line 127](https://github.com/larsk21/lean-praktikum-while/blob/687460dbe14b487bcb6bc7b73c0d70cc20b402a4/TBA/While/Solution.lean#L127) to fail.

**Comment by larsk21** [comment]
If you reorder the macro rules for `[Expr|true]` and `[Expr|false]`, the same thing will happen with true.

**Comment by larsk21** [comment]
This turned out to be a bug in Lean, which is expected to be fixed in the next nightly release.
